import { cn } from '@/lib/utils';
import { ClaudeMark } from '@/components/claude-mark';

interface ClaudeBadgeProps {
  variant?: 'chip' | 'inline';
  label?: string;
  className?: string;
}

export function ClaudeBadge({
  variant = 'inline',
  label = 'Powered by Claude',
  className,
}: ClaudeBadgeProps) {
  const title =
    'Generated by Claude — every citation verified verbatim against the record. Draft for attorney review.';

  if (variant === 'chip') {
    return (
      <span
        title={title}
        className={cn(
          'inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-2.5 py-1 text-[11px] font-sans font-medium text-foreground/80',
          className,
        )}
      >
        <ClaudeMark />
        <span>{label}</span>
      </span>
    );
  }

  return (
    <span
      title={title}
      className={cn(
        'inline-flex items-center gap-1.5 text-[11px] font-sans text-muted-foreground',
        className,
      )}
    >
      <ClaudeMark />
      <span>{label}</span>
    </span>
  );
}
