import { useState } from 'react';
import { Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ClaudeBadgeProps {
  variant?: 'chip' | 'inline';
  label?: string;
  className?: string;
}

export function ClaudeBadge({
  variant = 'inline',
  label = 'Powered by Claude',
  className,
}: ClaudeBadgeProps) {
  const [broken, setBroken] = useState(false);
  const title =
    'Generated by Claude — every citation verified verbatim against the record. Draft for attorney review.';

  const mark = broken ? (
    <Sparkles className="h-3.5 w-3.5 text-[#C96442]" strokeWidth={2} aria-hidden />
  ) : (
    <img
      src="https://cdn.simpleicons.org/claude/C96442"
      alt=""
      className="h-3.5 w-3.5"
      onError={() => setBroken(true)}
    />
  );

  if (variant === 'chip') {
    return (
      <span
        title={title}
        className={cn(
          'inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-2.5 py-1 text-[11px] font-sans font-medium text-foreground/80',
          className,
        )}
      >
        {mark}
        <span>{label}</span>
      </span>
    );
  }

  return (
    <span
      title={title}
      className={cn(
        'inline-flex items-center gap-1.5 text-[11px] font-sans text-muted-foreground',
        className,
      )}
    >
      {mark}
      <span>{label}</span>
    </span>
  );
}
