/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as DocketRouteImport } from './routes/docket'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as IndexRouteImport } from './routes/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const DocketRoute = DocketRouteImport.update({
  id: '/docket',
  path: '/docket',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deadlines': typeof DeadlinesRoute
  '/docket': typeof DocketRoute
  '/draft': typeof DraftRoute
  '/orders': typeof OrdersRoute
  '/review': typeof ReviewRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deadlines': typeof DeadlinesRoute
  '/docket': typeof DocketRoute
  '/draft': typeof DraftRoute
  '/orders': typeof OrdersRoute
  '/review': typeof ReviewRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deadlines': typeof DeadlinesRoute
  '/docket': typeof DocketRoute
  '/draft': typeof DraftRoute
  '/orders': typeof OrdersRoute
  '/review': typeof ReviewRoute
  '/roster': typeof RosterRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deadlines' | '/docket' | '/draft' | '/orders' | '/review' | '/roster' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deadlines' | '/docket' | '/draft' | '/orders' | '/review' | '/roster' | '/search'
  id: '__root__' | '/' | '/deadlines' | '/docket' | '/draft' | '/orders' | '/review' | '/roster' | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeadlinesRoute: typeof DeadlinesRoute
  DocketRoute: typeof DocketRoute
  DraftRoute: typeof DraftRoute
  OrdersRoute: typeof OrdersRoute
  ReviewRoute: typeof ReviewRoute
  RosterRoute: typeof RosterRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docket': {
      id: '/docket'
      path: '/docket'
      fullPath: '/docket'
      preLoaderRoute: typeof DocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeadlinesRoute: DeadlinesRoute,
  DocketRoute: DocketRoute,
  DraftRoute: DraftRoute,
  OrdersRoute: OrdersRoute,
  ReviewRoute: ReviewRoute,
  RosterRoute: RosterRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
